fixtures:
  forge_modules:
    stdlib: 'puppetlabs-stdlib'
    apt: 'puppetlabs-apt'
    wget: 'puppet-wget'
    archive: "puppet-archive"    
    translate: "puppetlabs-translate"
  symlinks:
    kubernetes: "#{source_dir}"
