fixtures:
  forge_modules:
    stdlib: 'puppetlabs-stdlib'
    apt: 'puppetlabs-apt'
    puppet_conf: 'puppetlabs-puppet_conf'
    archive: "puppet-archive"
    augeasproviders_sysctl: "herculesteam-augeasproviders_sysctl"
    augeasproviders_core: "herculesteam-augeasproviders_core"
    kmod: "puppet-kmod"
    helm: 'puppetlabs-helm'
    rook: 'puppetlabs-rook'
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision:
      repo: 'https://github.com/puppetlabs/provision.git'
      ref: 'f0e34b72ddb932386785fe828da7310fe12592e4'
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
    augueas_core:
      repo: https://github.com/puppetlabs/puppetlabs-augeas_core.git
      puppet_version: ">= 6.0.0"
  symlinks:
    kubernetes: "#{source_dir}"
