---
.gitlab-ci.yml:
  delete: true

appveyor.yml:
  delete: true

Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        version: '= 1.15.2'

Rakefile:
  changelog_user: puppetlabs
  changelog_since_tag: '4.0.0'
  extras:
    - |
      require 'rspec/core/rake_task'
      namespace :kubernetes do
        RSpec::Core::RakeTask.new(:integration) do |t|
          t.pattern = 'spec/acceptance/**{,/*/**}/*_spec.rb'
          t.rspec_opts = "--tag integration"
        end
      end
  extra_disabled_lint_checks:
    - parameter_documentation
    - params_empty_string_assignment
    - file_ensure
    - variables_not_enclosed

.rubocop.yml:
  include_todos:
    inherit_from: '.rubocop_todo.yml'
  profiles:
    strict:
      configs:
        AllCops:
          TargetRubyVersion: '2.5'
          Exclude:
          - tooling/kube_tool/*
          - tooling/*
          - spec/*
          - rakelib/*
          - plans/*.pp
          - tasks/*

spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true
  hiera_config_ruby: File.expand_path(File.join(File.dirname(__FILE__), 'fixtures/hiera/hiera.yaml'))
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/nightly.yml:
  unmanaged: true
.github/workflows/pr_test.yml:
  unmanaged: true
.github/workflows/auto_release.yml:
  unmanaged: false
.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: false
.github/workflows/release.yml:
  unmanaged: false
.travis.yml:
  delete: true
