#!/bin/sh
KEY_SIZE="${KEY_SIZE:-2048}"

/etc/k8s/kube_tool.rb -o ${OS} -v ${VERSION} -r ${CONTAINER_RUNTIME} -c ${CNI_PROVIDER}\
 -p ${CNI_PROVIDER_VERSION} -i ${ETCD_INITIAL_CLUSTER} -t ${ETCD_IP} -a ${KUBE_API_ADVERTISE_ADDRESS}\
 -d ${INSTALL_DASHBOARD} -b ${KEY_SIZE}
